name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      
      - name: Run linting
        run: ./gradlew --no-daemon checkstyleMain || true
        continue-on-error: true
      
      - name: Upload checkstyle reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: checkstyle-reports
          path: build/reports/checkstyle/